config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root "doctors#home"
  
  resources :patients
  resources :doctors do
    resources :appointments, only: [:index,:new, :create, :edit, :update, :destroy]
    
  end

  resources :patients do
    resources :notes 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  validates :date, presence: true
  validates :time, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :patients, through: :appointments

    validates :name, presence: true
    validates :phone, presence: true
    validates :school, presence: true
    
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :patient

  validates :message, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :doctors, through: :appointments

    has_many :notes, dependent: :destroy
    has_many :users, through: :notes

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :dob, presence: true
    validates :phone, presence: true
    validates :street, presence: true
    validates :city, presence: true
    validates :zip, presence: true

    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :notes, dependent: :destroy
  has_many :patients, through: :notes


  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    add_flash_types :info, :error, :warning

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

    def full_name
        "#{current_user.first_name} #{current_user.last_name}"
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show]
  before_action :set_doctor
  before_action :set_patients, only: [:new, :create]
  require 'time'
  def index
    @appointments = @doctor.appointments.order(:date, :time).paginate(page: params[:page],per_page: 4)
  end


  def new
    @appointment = @doctor.appointments.new
  end

  def create
  
    @appointment = @doctor.appointments.new(appointment_params)
    datetime=("2000-01-01 " + (params[:appointment][:time]) + ":00:00").to_datetime
    

    @appt=Appointment.where("doctor_id = ? and date = ? and time = ?", params[:doctor_id], params[:appointment][:date], datetime).count
    @patient=Appointment.where("patient_id = ? and date = ? and time = ?", params[:appointment][:patient_id], params[:appointment][:date], datetime).count
    
    if @appt > 0 || @patient > 0

      if @appt>0
        redirect_to new_doctor_appointment_path, error: "Appointment have. Change other Time!"   
      else
        redirect_to new_doctor_appointment_path, error: "Other Doctor Appointment have. Change other Time!"   
      end
    else
      
      if @appointment.save
        redirect_to doctor_appointments_path
      else
        render :new
      end
    end
  end


  def edit
    @doctor=set_doctor
    @appointment=set_appointment
    @patient=set_patients
  end

  def update
    @appointment = Appointment.find(params[:id])

    datetime=("2000-01-01 " + (params[:appointment][:time]) + ":00:00").to_datetime
      
    @appt=Appointment.where("doctor_id = ? and date = ? and time = ?", params[:doctor_id], params[:appointment][:date], datetime).count
    @patient=Appointment.where("patient_id = ? and date = ? and time = ?", @appointment.patient_id, params[:appointment][:date], datetime).count
    
    if @appt > 0 || @patient > 0

      if @appt>0
        redirect_to edit_doctor_appointment_path, error: "Appointment have. Change other Time!"   
      else
        redirect_to edit_doctor_appointment_path, error: "Other Doctor Appointment have. Change other Time!"   
      end
    else
      
      if @appointment.update(appointment_params)
        redirect_to doctor_appointments_path
      else
        render :edit
      end
    end
  end
  

  def destroy
    @doctor.appointments.find(params[:id]).destroy
    redirect_to doctor_appointments_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:doctor_id])
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def set_patients
      @patients = (Patient.all.order("last_name") - @doctor.patients)
    end

    def appointment_params
      params.require(:appointment).permit(:patient_id, :date, :time)
    end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  def index
    @doctors = Doctor.all.paginate(page: params[:page],per_page: 4)
    
  end

  def new
     @doctor = Doctor.new
    
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path
    else
      flash[:error] = 'Failed to add new doctor!'   
      render :new
    end
  end
  
  def edit
   
  end

  def update
    
    @doctor.update(doctor_params)

    if @doctor.save
      redirect_to doctors_path
    else
      flash[:error] = 'Failed to add Edit doctor!'   
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :specialty, :school, :phone)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :set_note, only: [:edit, :update, :destroy]
  before_action :set_patient
  
  def index
    @notes = @patient.notes.order("created_at")
  end

  def new
    @note = @patient.notes.new
  end

  def create
    @note = @patient.notes.new(note_params)
    @note.update(user_id: current_user.id)
    if @note.save
      redirect_to @patient
    else
      render :new
    end
  end

  def edit
  end

  def update
    @note = Note.find(params[:id])
    @note.update(user_id: current_user.id)
    if @note.update(note_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to @patient
  end

   private

    def set_note
      @note = Note.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def note_params
      params.require(:note).permit(:message, :user_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index
    @patients = Patient.all.order("last_name").paginate(page: params[:page],per_page: 4)
  end

  def show
    @appointments = @patient.appointments.order("date", "time")
    @notes = @patient.notes.all.order("created_at")
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      age = Date.today.year - @patient.dob.year
      @patient.update(age: age)
      redirect_to patients_path
    else
      render :new
    end
  end

  def edit
   
  end

  def update
    
    @patient.update(patient_params)

    if @patient.save
      redirect_to patients_path
    else
      flash[:error] = 'Failed to add Edit doctor!'   
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end
  
  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :age, :dob, :language, :sex, :phone, :street, :city, :state, :zip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/edit.html.erb
<div class="ui container body-container">

<% if @appointment.errors.any? %>
  <div>
    <ol style="color:red;font-size:20px;font-style:italic;">
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>

<% if error.present? %>
    <p class="alert alert-danger"><%= error %></p>
<% end %>

<h1>Edit Appointment</h1>
<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form" ) do |f| %>
  
  
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br />
  <%= f.label :time %>
  <%= f.select "time", (9..20).to_a %>
  <br />
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>
</div>

app/views/appointments/index.html.erb
<div class="ui container body-container">
<span class="doctor-show-header"><h1><%= @doctor.name %> Appointments</h1><h3>Specialty: <%= @doctor.specialty %></h3></span>

<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor), class:"ui button blue inverted" %>
<br />
<br />
<hr />


<table class="ui celled table">
  <thead>
    <th>Patient Name</th>
    <th>Patient Age</th>
    <th>Patient Date of Birth</th>
    <th>Appointment Date</th>
    <th>Appointment Time</th>
    <th>Update</th>
    <th>Remove</th>
  </thead>
  <tbody>
    <% @appointments.each do |appt| %>
      <tr>
        <td><%= link_to appt.patient.full_name, patient_path(appt.patient), class: "ui blue button inverted"%></td>
        <td><%= appt.patient.age %></td>
        <td><%= appt.patient.dob %></td>
        <td><%= appt.date.strftime('%a, %b %d, %Y') %></td>
        <td><%= appt.time.strftime("%l:%M %p")  %></td>
        
        <td><%= link_to 'Update', edit_doctor_appointment_path(appt.doctor_id, appt.id), class:"ui blue button inverted" %></td>
        <td><%= button_to 'Remove', doctor_appointment_path(appt.doctor_id, appt.id), method: :delete, class:"ui button red inverted" %></td>
      </tr>
    <% end %>
  </tbody>

</table>
<%= will_paginate @doctors %>
</div>

app/views/appointments/new.html.erb
<div class="ui container body-container">

<% if @appointment && @appointment.errors.any? %>
  <div>
    <ol style="color:red;font-size:20px;font-style:italic;">
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>

<% if error.present? %>
    <p class="alert alert-danger"><%= error %></p>
<% end %>

<h1>New Appointment</h1>
<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, @patients.collect { |p| [p.full_name, p.id]} %>
  <br />
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br />
  <%= f.label :time %>
  <%= f.select "time", (9..20).to_a %>
  <br />
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

</div>

app/views/doctors/edit.html.erb
<div class="ui container body-container">
<% if @doctor.errors.any? %>
  <div>
    <ol style="color:red;font-size:20px;font-style:italic;">
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>
  <h1>Edit Doctor</h1>
  <%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name,  placeholder: "Doctor Name" %>
    </div>
    <div class="field">
      <%= f.label :phone %>
      <%= f.phone_field :phone, placeholder: "Phone" %>
    </div>
    <div class="field">
      <%= f.label :school %>
      <%= f.text_field :school,  placeholder: "School" %>
    </div>
    <div class="field">
      <%= f.label :specialty %>
      <%= f.select :specialty, ["Allergy & Immunology", "Anesthesiology", "Dermatology", "Diagnostic Radiology", "Emergency Medicine", "Family Medicine", "Internal Medicine", "Medical Genetics", "Neurology", "Nuclear Medicine", "Obstetrics and Gynecology", "Opthamology", "Pathology", "Pediatrics", "Physical Medicine & Rehabilation", "Preventice Medicine", "Psychiatry", "Radiation Oncology", "Surgery", "Urology"]%>
    </div>
    <%= f.submit nil, class: "ui green button inverted" %>
  <% end %>
</div>

app/views/doctors/home.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="2000">

  <div class="carousel-inner">
    <div class="carousel-item active">
        <%= image_tag("slide.jpg", :alt => "First Slide",class:"d-block w-100") %>
    </div>
    <div class="carousel-item">
        <%= image_tag("slide1.jpg", :alt => "Second Slide",class:"d-block w-100") %>
    </div>
    <div class="carousel-item">
        <%= image_tag("slide2.jpg", :alt => "Third Slide",class:"d-block w-100") %>
    </div>
    <div class="carousel-item">
        <%= image_tag("slide3.jpg", :alt => "Fourth Slide",class:"d-block w-100") %>
    </div>
    <div class="carousel-item">
        <%= image_tag("slide4.jpeg", :alt => "Five Slide",class:"d-block w-100") %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/doctors/index.html.erb
 <div class="ui container body-container">
  <span class="doctor-show-header"><h1>Healthcare Doctor List</h1><h3>Number of Doctors: <%= @doctors.count %></h3></span>
  <%= link_to 'Add Doctor', new_doctor_path, class: "ui button blue inverted" %>
  <hr />

  <table class="ui selectable celled striped table padded">
    <thead>
      <th class="center aligned">Doctor Name</th>
      <th class="center aligned">Specialty</th>
      <th class="center aligned">Education</th>
      <th class="center aligned">Phone</th>
      <th class="center aligned">Appointments</th>
      <th class="center aligned">Update</th>
      <th class="center aligned">Remove</th>
    </thead>
    <tbody>
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= link_to doctor.name, doctor_appointments_path(doctor), class: "ui button blue inverted" %></td>
          <td><%= doctor.specialty %></td>
          <td><%= doctor.school %></td>
          <td><%= doctor.phone %></td>
          <td><%= doctor.appointments.count %></td>
          <td><%= button_to 'Update', edit_doctor_path(doctor), method: 'get', class:"ui button blue inverted"%></td>
          <td><%= button_to 'Remove', {:controller => :doctors, :action => 'destroy', :id => doctor.id }, :method => :delete, class:"ui button red inverted" %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
  <%= will_paginate @doctors %>
  </div>

app/views/doctors/new.html.erb
<div class="ui container body-container">

<% if @doctor.errors.any? %>
  <div>
    <ol style="color:red;font-size:20px;font-style:italic;">
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>

  <h1>Add Doctor</h1>
  <%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name,  placeholder: "Doctor Name" %>
    </div>
    <div class="field">
      <%= f.label :phone %>
      <%= f.phone_field :phone, placeholder: "Phone" %>
    </div>
    <div class="field">
      <%= f.label :school %>
      <%= f.text_field :school, placeholder: "School" %>
    </div>
    <div class="field">
      <%= f.label :specialty %>
      <%= f.select :specialty, ["Allergy & Immunology", "Anesthesiology", "Dermatology", "Diagnostic Radiology", "Emergency Medicine", "Family Medicine", "Internal Medicine", "Medical Genetics", "Neurology", "Nuclear Medicine", "Obstetrics and Gynecology", "Opthamology", "Pathology", "Pediatrics", "Physical Medicine & Rehabilation", "Preventice Medicine", "Psychiatry", "Radiation Oncology", "Surgery", "Urology"]%>
    </div>
    <%= f.submit nil, class: "ui green button inverted" %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg " style="background-color:  #EDC7B7;" >
  <a class="navbar-brand" >HospitalRecordSystem</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="http://localhost:3000/">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="http://localhost:3000/doctors">Doctors</a>
    </li>
    
    <li class="nav-item active">
      <a class="nav-link " href="http://localhost:3000/doctors/new">Add Doctors</a>
    </li>
  <li class="nav-item active">
      <a class="nav-link" href="http://localhost:3000/patients">Patients</a>
    </li>
    
    <li class="nav-item active">
      <a class="nav-link " href="http://localhost:3000/patients/new">Add Patients</a>
    </li>
  </ul>
  <% if user_signed_in? %>
        <div class="user-login">
            <%= "Welcome #{current_user.full_name}" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"logout"%>
        </div>
  <% end %>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon-heartbeat.ico'), :rel => 'icon', :type =>  'image/ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body style="background-color:#EFE2BA;">
    <%= render 'layouts/navbar' %>
    
    
      <%= yield %>
    
  </body>
</html>

app/views/notes/edit.html.erb
<div class="ui container body-container">

<% if @note.errors.any? %>
  <div>
    <ol style="color:red;font-size:20px;font-style:italic;">
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>

<h1>Edit Note For <%= @patient.full_name %></h1>
<%= form_with(model: [@patient,@note], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message, placeholder: "Message", rows: 10%>
  </div>
  <%= f.submit nil, class: "ui blue button" %>
<% end %>
</div>

app/views/notes/new.html.erb
<div class="ui container body-container">

<% if @note.errors.any? %>
  <div>
    <ol style="color:red;font-size:20px;font-style:italic;">
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>

<h1>Add Note For <%= @patient.full_name %></h1>
<%= form_with(model: [@patient, @note], local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message, placeholder: "Message", rows: 10, autofocus: true %>
  </div>
  <%= f.submit nil, class: "ui blue button" %>
<% end %>
</div>

app/views/patients/index.html.erb
<div class="ui container body-container">
<span class="doctor-show-header"><h1>Healthcare Patient List</h1><h3>Number of Patients:  <%= @patients.count %></h3></span>
<%= link_to 'Add Patient', new_patient_path, class:"ui button blue inverted"%>
<br />
<br />
<hr />

<table class="ui celled table selectable striped padded">
  <thead>
    <th class="center aligned">Patient Name</th>
    <th class="center aligned">Age</th>
    <th class="center aligned">Date of Birth</th>
    <th class="center aligned">Sex</th>
    <th class="center aligned">Phone</th>
    <th class="center aligned">City</th>
    <th class="center aligned">State</th>
    <th class="center aligned">Zip</th>
    <th class="center aligned">Preferred Language</th>
    <th class="center aligned">Update</th>
    <th class="center aligned">Remove</th>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.full_name, patient_path(patient), class: "ui button blue inverted" %></td>
        <td><%= patient.age %></td>
        <td><%= patient.dob.strftime('%m/%d/%Y') %></td>
        <td><%= patient.sex == "Male" ? "M" : "F" %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.city %></td>
        <td><%= patient.state %></td>
        <td><%= patient.zip %></td>
        <td><%= patient.language %></td>
        <td><%= button_to 'Update', edit_patient_path(patient), method: 'get', class:"ui button blue inverted"%></td>
        <td><%= button_to 'Remove', {:controller => :patients, :action => 'destroy', :id => patient.id }, :method => :delete, class:"ui button red inverted" %></td>
      </tr>
    <% end %>
  </tbody>

</table>
<%= will_paginate @doctors %>
</div>

app/views/patients/show.html.erb
<div class="ui container body-container">
<h1><%= @patient.full_name%></h1>
<h2 class="ui center aligned blue header">Patient Information</h2>
<table class="ui definition table user-info selectable">
<tr>
    <td>First Name:</td>
    <td><%= @patient.first_name %></td>
</tr>
<tr>
    <td>Last Name:</td>
    <td><%= @patient.last_name %></td>
</tr>
<tr>
    <td>Age:</td>
    <td><%= @patient.age %></td>
</tr>
<tr>
    <td>Date of Birth:</td>
    <td><%= @patient.dob.strftime('%m / %d / %Y') %></td>
</tr>
<tr>
    <td>Sex:</td>
    <td><%= @patient.sex %></td>
</tr>
<tr>
    <td>Phone:</td>
    <td><%= @patient.phone %></td>
</tr>
<tr>
    <td>Street:</td>
    <td><%= @patient.street %></td>
</tr>
<tr>
    <td>City:</td>
    <td><%= @patient.city %></td>
</tr>
<tr>
    <td>State:</td>
    <td><%= @patient.state %></td>
</tr>
<tr>
    <td>Zip:</td>
    <td><%= @patient.zip %></td>
</tr>
<tr>
    <td>Preffered Language:</td>
    <td><%= @patient.language %></td>
</tr>
<tr>
    <td>Update Patient:</td>
    <td><%= button_to 'Update', edit_patient_path(@patient), method: 'get', class:"ui button blue inverted"%></td>
</tr>
<tr>
    <td>Remove Patient:</td>
    <td><%= button_to 'Delete', {:controller => :patients, :action => 'destroy', :id => @patient }, :method => :delete, class:"ui button red inverted" %></td>
</tr>
</table>
<br />
<br />

<h2 class="ui center aligned blue header"><%= @patient.full_name%> <%= @patient.last_name[-1] == 's' ? "'  Scheduled Appointments" : "\'s Scheduled Appointments"%></h2>

    <table class="ui table striped selectable">
        <thead>
            <tr>
                <th>Doctor Name</th>
                <th>Specialty</th>
                <th>Doctor Phone</th>
                <th>Date</th>
                <th>Time</th></th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
            <% @appointments.each_with_index do |appt,i| %>
                <tr>
                    <td><%= link_to appt.doctor.name, doctor_appointments_path(appt.doctor),class:"ui button blue inverted" %></td>
                    <td><%= appt.doctor.specialty %></td>
                    <td><%= appt.doctor.phone %></td>
                    <td><%= appt.date.strftime('%a, %b %d, %Y') %></td>
                    <td><%= appt.time.strftime("%l:%M %p") %></td>
                    <td><%= button_to 'Remove', doctor_appointment_path(appt.doctor_id, appt.id), method: :delete, class:"ui button red inverted" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>


<div class="notes-container">
    <h2 class="ui center aligned blue header"><%= @patient.full_name%> <%= @patient.last_name[-1] == 's' ? "'  Doctor Notes" : "\'s Doctor Notes"%></h2>
    <p><%= @notes.length <= 0 ? "No patient notes found": ""%></p>
    
    <% @notes.each do |note|  %>
        <div class="note">
            <p class="message-body"><%= note.message %></p>
            <div class="poster-info">
                <%= note.user.full_name %>
                <br />
                <%= note.created_at.strftime("%b %d, %Y") %>
                <br />
                <%= note.created_at.in_time_zone("Central Time (US & Canada)").strftime("%l:%M %p") %>
            </div>
            <div class="note-actions">
                <%= link_to edit_patient_note_path(note.patient_id, note), :edit => 'go' do %>
                    <i class="edit outline icon"></i>
                <% end %>
                <%= button_to patient_note_path(note.patient, note), method: :delete do %>
                    <i class="trash alternate icon trash"></i>
                <% end %>
                
            </div>
            
        </div>
    <% end %>
    <%= link_to "Add Note", new_patient_note_path(@patient), class:"ui button blue" %>
    
</div>  
</div>